
theme: jekyll-theme-midnight
title: Constitutions of the World
description: Finding the link between the prosperity and Constitution of a nation 
menu: [
{'name': 'Home', 'pagename': 'index'},
{'name': 'sharks here !', 'pagename': 'Constitutions of the World'},
{'name': 'Go there', 'pagename': 'page2'},
{'name': 'Yet Another page', 'pagename': 'page3'},
]
